### ISSUE TITLE
SPFx Extension does not generate scaffolding for project?  What pre-reqs needed to set up first?

### ISSUE THREAD

**Issue by nyannios** [SharePoint/sp-dev-fx-vs-extension#14]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
[ x ] Question
[ x ] Bug
[ x ] Enhancement

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

When creating a new SPFx project Visual Studio 2017 with the SPFx extension, we get this error: 

'yo' is not recognized as an internal or external command,
operable program or batch file.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

'yo' is not recognized as an internal or external command,
operable program or batch file.

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

New Install of Visual Studio 2017 enterprise with the SPFx extension.
Create SPFx Project for Web part but get error above

1. What are the path prerequisites yeoman, npm, gulp, etc on Windows 10 prior to using Visual Studio to 
     create SPFx WebParts and Extensions?
2. Can they be installed globally rather than on every project?
3. Is there a SETUP script/PowerShell that can set up all the prerequisites first or is this documented?

[SPFX.zip](https://github.com/SharePoint/sp-dev-fx-vs-extension/files/1229040/SPFX.zip)

Thank you

Nick

**Comment by pschaeflein** [comment]
The pre-requisites are detailed in the [README.md](https://github.com/SharePoint/sp-dev-fx-vs-extension/blob/master/README.md) file.

**Comment by nyannios** [comment]
Got it - Thanks!
