### ISSUE TITLE
Visual Studio not responding when creating new SPFx project

### ISSUE THREAD

**Issue by gonadn** [SharePoint/sp-dev-fx-vs-extension#15]
Observed Behavior

Only a few files and folders are created (bin, obj and the project file), and the process never completes. Visual studio 2017 are not responding. Using .NET framework 4.6.1 in VS 2017 pro. VS just hanging on creating the project and never get finished, you have to just kill the process, close VS.

Steps to Reproduce

Create new SPFx web part project, select name and location, select component name and start generating.....

Ref issue: [https://github.com/SharePoint/sp-dev-fx-vs-extension/issues/10](url)

I did as @Ahmad-Gad described but still not working.
I uninstalled VS and installed again, dident help, i even installed vs on my second computer, still same issue....

**Comment by solutionprovider27** [comment]
having same issue with me on VS 2017 15.4 Community edition and VS 2015 Enterprise Edition .

**Comment by pschaeflein** [comment]
Please respond with the installed version of the generator using the following:

`npm list -g @microsoft/generator-sharepoint`

**Comment by gonadn** [comment]
![npm](https://user-images.githubusercontent.com/3224441/30127958-473221ac-9341-11e7-8256-9cbbe8001b39.PNG)

**Comment by gonadn** [comment]
i just tried to create a SPFx project, and as i mentioned above VS is hanging / freezed . i waited for at least 5 min before i had to just kill the process.
![vs](https://user-images.githubusercontent.com/3224441/30128378-bd534806-9342-11e7-829f-266a14d71317.PNG)

Folder structure looks like:
![folder](https://user-images.githubusercontent.com/3224441/30128431-f1dde68a-9342-11e7-82b2-6ad4ffd4d566.PNG)

**Comment by pschaeflein** [comment]
The latest version of the generator has caused this issue. Thanks for reporting it.

**Comment by gonadn** [comment]
I tried the workaround as you described, VS finished creating the project, but when i open the project it look like:
![pj](https://user-images.githubusercontent.com/3224441/30130480-994193b2-9349-11e7-8704-9521fd43c35d.PNG)

none of the folders or files are loaded...

**Comment by gonadn** [comment]
a workaround for loading all folders is to use VS option "Add Existing Project", navigate to newly generated project, select prosject file .csproj and it will load the project, but still you will not se any folders. You have to click on "Show All Files" option in Solution Explorer and select one by one and "Include In Project".....But then VS hangs on "Not Responding".....

**Comment by pschaeflein** [comment]
Another possible work-around. On the advanced tab, add the "skipFeatureDeployment" option to the command-line shown.

> yo @microsoft/sharepoint --solutionName "hello-world" --framework "react" --componentType "webpart" --componentName "HelloWorld" --componentDescription "HelloWorld web part" skipFeatureDeployment true

**Comment by gonadn** [comment]
oki thanks, but when will this bug be fixed?

**Comment by eshupps** [comment]
We are working on it. In the meantime, you may explicitly get a previous version of the yeoman generator that does not include the new prompt or use the workaround described by Paul.

**Comment by gonadn** [comment]
Best workaround for is to just remove the new generator:

npm rm -g @microsoft/generator-sharepoint

and install the previous version:
npm install -g @microsoft/generator-sharepoint@1.1.3

**Comment by gonadn** [comment]
any fix on this bug?
