### ISSUE TITLE
Add support for Extensions

### ISSUE THREAD

**Issue by pschaeflein** [SharePoint/sp-dev-fx-vs-extension#19]
Add support for SPFx Extensions, targetting @microsoft/generator-sharepoint v1.3.2

**Comment by punjabimundaaa** [comment]
+1

**Comment by pschaeflein** [comment]
This support is available in the latest VSIX release: https://github.com/SharePoint/sp-dev-fx-vs-extension/releases/tag/1.3.2

It is marked as pre-release while we do some further testing. Your feedback is appreciated.
