### ISSUE TITLE
Can't install extensions because of "prerequisites that cannot be resolved"

### ISSUE THREAD

**Issue by BigEaseGueldi** [SharePoint/sp-dev-fx-vs-extension#23]
#### Category
[x ] Question
[ ] Bug
[ ] Enhancement

#### Versions
Visual Studio version:  Enterprise 2017, 15.4.1
SPFx Generator version: 1.3.2

#### Expected or Desired Behavior
I'd like to install the package. ;-)

#### Observed Behavior
The VSIX Installer fails for me, saying that "The extension cannot be installed to this product due to prerequisites that cannot be resolved"

#### Steps to Reproduce
(hopefully I'm the only one)

Please let me know what's missing - the previous version worked like a charm.

![2017-10-26 18_17_04-vsix installer](https://user-images.githubusercontent.com/17311219/32064666-cd76ba7e-ba7a-11e7-8dee-d20057e468ea.png)

Thanks for your help!
Dirk

**Comment by pschaeflein** [comment]
That is a VS pre-req (I think). We are supporting VS2015, so we have a reference to Microsoft.VisualStudio.Shell.14 Version=14.0. The package contains that assembly, but looks like we need to do some cleanup.

If you are in a hurry, you could try downloading via the [isolated shell](http://go.microsoft.com/fwlink/?LinkId=616021), but be advised, I've never done that. ;)

**Comment by BPerdriau** [comment]
Hello,

I have the same error on installation with both VS 2017 Community and Enterprise, 15.4.1, up to date.
I tried downloading it from Marketplace and GitHub, some behaviour.

If it can help to troubleshooting, no hurry from me :)

Good job so far !

**Comment by pschaeflein** [comment]
Updated release posted to GitHub: https://github.com/SharePoint/sp-dev-fx-vs-extension/releases/tag/v1.3.3

Please try installation again and report back.

**Comment by filionf** [comment]
I had the same issue and the update from GitHub installed successfully on VS2017.

**Comment by BPerdriau** [comment]
I downloaded from GitHub and it's ok for me on VS2017 Community / Enterprise.
Thank you !

**Comment by BigEaseGueldi** [comment]
Works for me as well! Thanks for the very quick fix!

**Comment by MikaBerglund** [comment]
That updated release worked for me too. Thanks!

**Comment by khha** [comment]
I have the same issue when you download the vsix file from the marketplace. When you download version 1.3.3 from github it works: https://github.com/SharePoint/sp-dev-fx-vs-extension/releases/tag/v1.3.3

**Comment by VSuser2019** [comment]
> Updated release posted to GitHub: https://github.com/SharePoint/sp-dev-fx-vs-extension/releases/tag/v1.3.3
> 
> Please try installation again and report back.

I am having the same issue, but 1.3.3 fix from GitHub didn't resolve the issue. I am still getting the same error. Any help will be appreciated.

Thanks,

**Comment by eshupps** [comment]
Version 1.3 is too old for VS 2019 support. Upgrade your Yeoman instance to 1.8.x and install the latest version of the extension from the marketplace or from the releases page in this repo.

**Comment by VSuser2019** [comment]
Microsoft SQL Server Data Tools for Visual Studio 2017  (SSDT)
Version 15.9.11
VisualStudio.15.Release/15.9.11+28307.586
Microsoft .NET Framework
Version 4.7.02556

Installed Version: IDE Standard

I don't have VS2019.

**Comment by pschaeflein** [comment]
Perhaps your user name is a bit confusing..  :)

Regardless, version 1.3 of the SPFx toolchains is quite old. Is there any particular reason you are using that version? 

The latest release of this tool will support Visual Studio 2017.

**Comment by VSuser2019** [comment]
I was researching for a fix and came across your suggestion. I am an amateur user and trying to get the extension to work with current download SSDT 2017. 2019 represent the year and sorry about the username, I just created. :)

**Comment by pschaeflein** [comment]
It will not work with SSDT. You need to install the full Visual Studio product.

The Community (free) version will work.

https://visualstudio.microsoft.com/

**Comment by VSuser2019** [comment]
Let me provide a background maybe it will help clarify what I am trying to do.

I am trying to modify the Change request template using the CMMI framework on Team Foundation Server 2017. Therefore, I installed VS SSDT 2017. We need to use an extension/plug in to modify template form using MSFT.TFSProcessTemplateEditor from link 
https://marketplace.visualstudio.com/items?itemName=KarthikBalasubramanianMSFT.TFSProcessTemplateEditor

After installing VS SSDT 2017, and later the plugin, I am getting the original error from this forum.

**Comment by VSuser2019** [comment]
I have just installed VS 2019, and I attempt to install the plugin mention above which I believe is only meant for VS 2017 as the plugin still not being recognized for VS 2017 or 2019.  Any help is welcome.

Thank you

**Comment by pschaeflein** [comment]
This issue relates to v1.3 of this extension. Please use the latest version of the extension.

If you have an issue with v1.8 of the extension, please open an new issue. This issue is closed.
