### ISSUE TITLE
cant install extension for vs2017

### ISSUE THREAD

**Issue by dariuszbz** [SharePoint/sp-dev-fx-vs-extension#26]
I'm getting:
![image](https://user-images.githubusercontent.com/19564162/35097800-93bd322a-fc49-11e7-848f-b66cfd90d5d0.png)

my vs2017 is:
![image](https://user-images.githubusercontent.com/19564162/35097818-b137e9bc-fc49-11e7-8de1-c6eea48cd9a4.png)

thank you for any help.

**Comment by pschaeflein** [comment]
This is known issue with VS 15.3 that was resolved in the [latest release](https://github.com/SharePoint/sp-dev-fx-vs-extension/releases/tag/1.4.0).

I will test w/15.5. Where did you get the VSIX file? Is this a new install or after upgrading Visual Studio?

**Comment by dariuszbz** [comment]
I got from marketplace.

**Comment by pschaeflein** [comment]
The Visual Studio marketplace has been updated with v1.5.
