### ISSUE TITLE
Yeoman generator not found issue while creating the Project.

### ISSUE THREAD

**Issue by mokhtarbepari** [SharePoint/sp-dev-fx-vs-extension#27]
#### Create a SPx WebPart using VS 2015 Extension
[Yeoman generator not found issue while creating the Project. ] Bug

#### Versions
[ Visual Studio 2015   ]  Visual Studio version (Help > About)
[    ]  SPFx Generator version (`1.3.x)

![image](https://user-images.githubusercontent.com/8001690/35801309-d8564d76-0a91-11e8-8130-778c5a9f44d5.png)

#### Expected or Desired Behavior
Create the SharePoint Framework Project

#### Observed Behavior
Error while creating the Project

#### Steps to Reproduce
1. Install Visual Studio Extension
2. Open Visual Studio 2015, select SharePoint Framework Project Template.

**Comment by pschaeflein** [comment]
If you could please complete the section with the version information as well as the repro steps, that would be helpful. 

The template is expected to be completed, with unnecessary sections removed before submitting.

Thank you.

**Comment by mokhtarbepari** [comment]
Thanks for information.  I got the solution.  Upgraded NPM, upgraded @microsoft/generator-sharepoint to 1.4.0 resolved the issue.
