### ISSUE TITLE
On Premise webpart creation - hang forever visual studio 2017

### ISSUE THREAD

**Issue by vinny-Jo** [SharePoint/sp-dev-fx-vs-extension#28]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Category
[ ] Question
[* ] Bug
[ ] Enhancement

#### Versions
[  2017 Enterprise 15.5.7  ]  Visual Studio version (Help > About)
[  1.4.1  ]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)
[ 8.10] Node js

#### Expected or Desired Behavior
Create the new SPFX project (webpart) on premise

#### Observed Behavior
create new project by selecting spfx project
on the SPFX popup I selected "onprem"
specified the name and description of my webpart. 
Click generate.... and visual studio hang on (Creating project popup) forever.

The project has been generated... 
- no dll reference.
- the project is not attached to the solution file.
- npm has not run

#### Steps to Reproduce
create new project by selecting spfx project
on the SPFX popup I selected "onprem"
specified the name and description of my webpart. 
Click generate.... and visual studio hang on (Creating project popup) forever.

**Comment by eshupps** [comment]
Have you updated to the latest version of the SPFx Yeoman Generator? 

npm install @microsoft/generator-sharepoint@latest -g

**Comment by pschaeflein** [comment]
Another debugging tip -- on the Advanced tab, choose to "Show command window"

This will show the generator output as it runs and may include an error or other issue.

**Comment by vinny-Jo** [comment]
Hi,

Yes I have got the latest of yeoman.

It is only for on premise (it crash)

Visual studio froze… have to kill the session

Th folder structure looks ok… but the project references and the project is not attached

[cid:image002.png@01D3B6BB.7E8FF6E0]

Visual studio Hang… as below (I am running visual studio as administrator)

[cid:image003.png@01D3B6BB.7E8FF6E0]

**Comment by MatthiasAbt** [comment]
I have the same issue. 

When showing Command window, everything stays black. After pressing any key there was a message i have to confirm for sending Information (Y/n).  It tooks a while, but after closing the command window it works with my VS 2017.

**Comment by pschaeflein** [comment]
This appears to be a discrepency between the extension and the generator. Both have been updated to ver 1.5 this week, so please update and try again.
