### ISSUE TITLE
SharePoint framework template not showing while creating new project from VS 2015

### ISSUE THREAD

**Issue by K-SAHOO** [SharePoint/sp-dev-fx-vs-extension#30]
Hi,
I have VS 2015 Enterprise version just now installed. I got the framework project template from below url and installed successfully. When i try to create new SPFX project I do not see the installed framework template there on project creation wizard in visual studio.
https://github.com/SharePoint/sp-dev-fx-vs-extension/releases/tag/1.4.0 

#### Category
[ ] Question

#### Versions
[ 14.0.25431.01 Update 3  ]  Visual Studio version (Help > About)
[    ]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)
![image](https://user-images.githubusercontent.com/37403636/37460510-6beac682-2871-11e8-96fa-3a87a4f0e443.png)

#### Expected or Desired Behavior
Visual studio should display the SPFX framework project template while creating new project.

#### Observed Behavior
VS not showing SPFX framework project template in VS 2015.

#### Steps to Reproduce
Try to install the SPFX framework vsix from above url in your vs 2015 update 3 and post installation try to create a SPFX prject.

Thanks,
Kailash

**Comment by eshupps** [comment]
After installing the VSIX package, have you restarted Visual Studio? Also, have you gone through the SPFx setup instructions for Node/Gulp/Yeoman, etc. and are you able to create SPFx solutions from the command line successfully?

**Comment by pschaeflein** [comment]
Closed due to inactivity.
