### ISSUE TITLE
Question: How to debug SPFx Projects created using this extension in Visual Studio 2017?

### ISSUE THREAD

**Issue by jaiswati** [SharePoint/sp-dev-fx-vs-extension#31]
Hi 

Question: How to debug SPFx Projects created using this extension in Visual Studio 2017?

Best Regards,
Swati

**Comment by eshupps** [comment]
Debug the same way you would any Node-based solution in Visual Studio. See the following link for suggestions:

[https://stackoverflow.com/questions/34211004/how-can-i-debug-gulp-tasks-using-node-tools-for-visual-studio]https://stackoverflow.com/questions/34211004/how-can-i-debug-gulp-tasks-using-node-tools-for-visual-studio

Alter the paths and references accordingly for the way in which the Yeoman generator scaffolds the SPFx project.

**Comment by pschaeflein** [comment]
I would also add that you are actually debugging javascript in the browser. Using Visual Studio is optional for that, as most browsers have tools to aid in debugging.

**Comment by pschaeflein** [comment]
Closed due to inactivity.
