### ISSUE TITLE
Update SPFx Visual studio extension to support latest framework by default

### ISSUE THREAD

**Issue by nithinmohantk** [SharePoint/sp-dev-fx-vs-extension#32]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Category
[ ] Question
[ ] Bug
[X ] Enhancement

#### Versions
[ X   ]  Visual Studio version (Help > About)
[    ]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
Can we update the extension to support the latest version of the framework as default in project template?

#### Observed Behavior
The extension seems to be updated a few months ago and uses Sharepoint Framework version 1.3.2. 

#### Steps to Reproduce
Install version 1.3.3 of the framework with Visual Studio 2017 15.6 version. 

I could also contribute to the development of the extension further.

**Comment by pschaeflein** [comment]
The extension calls the generator that is installed on the machine. Unless the command-line parameters of the generator have changed, the extension should work. Are you seeing an error?

**Comment by pschaeflein** [comment]
Closed due to inactivity.
