### ISSUE TITLE
Error while installing the project template

### ISSUE THREAD

**Issue by Shamrh** [SharePoint/sp-dev-fx-vs-extension#34]
#### Category
[] Question
[X] Bug
[ ] Enhancement

#### Versions
Visual Studio Professional 2017 
[    ]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
Successful installation

#### Observed Behavior
Error due to pre-requisites that can not be resolved
![image](https://user-images.githubusercontent.com/32353229/40955864-7752965c-68aa-11e8-9408-de03064ee7f8.png)

**Comment by eshupps** [comment]
The only defined pre-requisites for the VSIX package are the Core editor and .NET Framework 4.5. It is scoped for Community, Professional and Enterprise editions from 14.0 - 16.0. As it appears you are on a compatible version, there must be something missing from the VS install that the VSIX framework is expecting. Can you post the Help > About page from your instance? And do you have another machine you can try it on?
