### ISSUE TITLE
SPFx Project creation hangs on Visual Studio 2017 Enterprise

### ISSUE THREAD

**Issue by joaosilva2313** [SharePoint/sp-dev-fx-vs-extension#36]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Category
[ ] Question
[ x] Bug
[ ] Enhancement

#### Versions
[  15.7.4  ]  Visual Studio version (Help > About)
[   1.5.1 ]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
Creates project

#### Observed Behavior
Visual studio becomes unresponsive, but creates the folders of the all project, but i cannot open it with the .csproj

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by joaosilva2313** [comment]
We already tried downgrading the spfx version to 1.4.1, and using the spfx project template 1.3.2
Still has the same problems.
We can create the projects using only the command line

**Comment by joaosilva2313** [comment]
Thanks for the answer Paul, but it didnt help.
I have the same problem in other machines, only the one's that we didnt install the update, are working.
[Issue SPFx Project Template.pdf](https://github.com/SharePoint/sp-dev-fx-vs-extension/files/2159377/Issue.SPFx.Project.Template.pdf)

Check the pdf I uploaded, it has the steps we are trying and the results

**Comment by eshupps** [comment]
In your issue description you state you are using the 1.5.1 version of the extension but then in your later comments you state that you have downgraded SPFx to 1.4.1. That's not going to work - you need to use SPFx 1.5.x with the 1.5.x version of the VS extension. Have you tried both of the most recent revisions together?

**Comment by joaosilva2313** [comment]
![image](https://user-images.githubusercontent.com/31274438/42232625-f2aa47da-7ee6-11e8-9a7b-0cea9b13a3f7.png)

Updated to latest version
![image](https://user-images.githubusercontent.com/31274438/42232676-17bf4bb0-7ee7-11e8-96e2-4ab154315658.png)

![image](https://user-images.githubusercontent.com/31274438/42232736-3eb324d0-7ee7-11e8-998a-4cceb6488268.png)

the same result... stuck...

**Comment by pschaeflein** [comment]
If you run with the command window visible, you should see what it is doing. In the past, an error would show, or a prompt for some reason. Is there anything like that happening?

**Comment by joaosilva2313** [comment]
![image](https://user-images.githubusercontent.com/31274438/42233342-31681a54-7ee9-11e8-865d-dce208cca1c6.png)

![image](https://user-images.githubusercontent.com/31274438/42233365-413b2f20-7ee9-11e8-9d0b-8ec9b1632f7f.png)

nothing...
this version creates a .yo-rc.json on the solution folder
its content is:
{
  "@microsoft/generator-sharepoint": {
    "solutionName": "MySPFxProject6",
    "environment": "onprem",
    "componentType": "webpart",
    "framework": "none",
    "componentName": "Test",
    "componentDescription": "Teste",
    "isCreatingSolution": true
  }
}

**Comment by joaosilva2313** [comment]
do you want me to send you the .csproj or .sln?

**Comment by eshupps** [comment]
We think we have identified the issue and are working on a fix.

**Comment by eshupps** [comment]
Fix included in commit #2296022. Note that you will need to use the latest public release from GitHub as the VS Gallery extension takes a few days to update.

https://github.com/SharePoint/sp-dev-fx-vs-extension/releases/tag/v1.5.1.1

**Comment by joaosilva2313** [comment]
Now its working, but only if we have the "show command window..." checked, and it only finishes the creation when the command window is closed

**Comment by lvasiliou** [comment]
I had the same issue so i installed the 1.5.1.1 release and i was still having the same problem. After selecting the option to display the command prompt window, turned out that yeoman was prompting Y/N for diagnostic feedback, preventing the script from running.

**Comment by eshupps** [comment]
There is no corresponding command line switch for the diagnostic feedback issue. An issue has been opened for this in the sp-dev-docs repo (see reference issue above). As soon as the product team resolves this discrepancy, we will update the extension accordingly. In the meantime, use the show command window option to complete project scaffolding.

**Comment by EdwKro** [comment]
I'm running into exactly the same problem. As soon as I try to generate a project; Visual studio freezes.

Now I see you guys talking about an advanced tab where I can select to show the command prompt. Where exactly is that? I can't seem to locate it.

Thanks for your time.

**Comment by pschaeflein** [comment]
Did you download the latest release from the GitHub releases tab? The marketplace version is not yet updated.


- Paul

Thumbed from my phone. Please forgive brevity and typos.

________________________________

**Comment by EdwKro** [comment]
I did, sadly still showing the same results.

I was hoping the command prompt would show me where the crash occurs, but as I said before; I cant seem to find the function.

**Comment by eshupps** [comment]
@EdwKro We have been unable to replicate the diagnostic prompt issue with v1.5.1 of the Yeoman Generator. Are you able to see our form at all or does it hang after specifying the solution directory? What version of Visual Studio are you using? Can you provide a screen shot?

**Comment by EdwKro** [comment]
@eshupps I could send you a screenshot of my crashing visual studio, but I doubt the greyed out screen with a loading bar will be very helpful.

I do see your generate window and am able to fill out the name and such. It all goes wrong as soon as I press generate.

Today I noticed that you added a side-note saying I should wait for at least 7 minutes. I am currently waiting over 14 minutes, and nothing has yet happened.

**Comment by eshupps** [comment]
@EdwKro If you can interact with the form then you can see the “Advanced” tab at the top. Before you click the button to generate the solution, open that tab, copy the command line and paste it here. Also, can you run the generator in the command window? If so, copy that output and also paste it here. And it would help to know what version of Visual Studio you are using.

**Comment by MichelLaplane** [comment]
Same here with the 1.5.1.2 and VS2017 15.7.5. VS2017 Never finishes project creation (creation of project dialog never closes) and you need to end VS2017 task using the ugly ctrl-alt-del command.

For the extension to work you need to check "Show command Window..." in the advanced tab.
It builds the project in few seconds. To finish the generator processing you need to close the command line (as stated in the dialog box).

Parameters used for generation : 
![image](https://user-images.githubusercontent.com/15141659/46344335-245c4200-c641-11e8-8dd4-bde4e23a853b.png)

**Comment by Rogerstigers** [comment]
I know this issue is closed, but I wanted to point out that this is still happening.  The solution is the same,open the console window and answer the prompts.  It's as if yoeman is ignoring the prompts passed in via the ui.

**Comment by eshupps** [comment]
Yes, there are some bugs in the Yeoman generator command-line for various releases. Update both the generator and the extension to version 1.8.x and these should be resolved (with the proviso that there are known issues with two of the options, the latest version provides some explanatory text for each one). We'll release a new update once Microsoft fixes the Yeoman command line issues.
