### ISSUE TITLE
Does not install on Visual Studio 2019

### ISSUE THREAD

**Issue by Omnicarpocalypse** [SharePoint/sp-dev-fx-vs-extension#40]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Category
[ ] Question
[X] Bug
[ ] Enhancement

#### Versions
[16.0.0]  Visual Studio version (Help > About)
[-- (empty)]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

I expected to be allowed to install it.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

I could not install it.

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

Run the latest version (1.7.0) Framework.VSIX.vsix with Visual Studio 2019 installed.

![image](https://user-images.githubusercontent.com/39909264/55490337-a08c0e00-5601-11e9-9a76-3adbb80fcdb7.png)

**Comment by eshupps** [comment]
Support for 2019 is included in the current repo targeted for generator 1.8.0.0. We’ll get a final release out soon and update the  extension in the marketplace shortly thereafter.

Eric A. Shupps
BinaryWave

US: 611 S. Main St. | Suite 400 | Grapevine, TX 76051 | P: +1 (888) 387-1197 x701 | F: +1 (817) 410-4602
UK: 5 Tivoli Walk | Cheltenham GL50 2UX | P: +44 (0)333 123 0258
Email: eshupps@binarywave.com
Web: www.binarywave.com
Blog: www.sharepointcowboy.com
Twitter: @eshupps
Facebook: www.facebook.com/sharepointcowboy
----------------------------------------------------
This communication may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended recipient, you are hereby notified that any disclosure, photocopying or distribution of these contents is unauthorized and prohibited. If you have received this in error,
________________________________
