### ISSUE TITLE
Project were not creating in visual studio 2017

### ISSUE THREAD

**Issue by flextrio-gandhi** [SharePoint/sp-dev-fx-vs-extension#41]
![ProjectNotCreating](https://user-images.githubusercontent.com/28822452/60968837-b2392c00-a33b-11e9-8f70-611406f9426f.PNG)
When iam trying to to create a new mvc or asp.net core projects, The project is not creating. I dont know the wat is the problem with visual studio

**Comment by eshupps** [comment]
The extension is only for creating SharePoint Framework projects. Other Visual Studio project templates are unrelated to the extension. If you are having trouble creating other projects after installing the extension, uninstall it, update Visual Studio if necessary, download the latest version from Releases or the Visual Studio marketplace, then try re-installing the extension.
