### ISSUE TITLE
Double files within explorer

### ISSUE THREAD

**Issue by bonm014** [SharePoint/sp-dev-fx-vs-extension#6]
#### Category
[ ] Question
[X] Bug
[ ] Enhancement

#### Observed Behavior
I create a new project in Visual Studio 2015 and a new web part within, the form shows and I fill in all the required fields. I leave the "Do not automatically install dependencies" is unchecked.
I close visual studio, reopen visual studio, load the project I just created and I see all the files double within the solution gallery.

#### Expected or Desired Behavior
I would expect that all my files are listed once, the project file (open in notepad) only shows a reference to the files once.

#### Steps to Reproduce
See observed behavior
![projectdefinition](https://cloud.githubusercontent.com/assets/7635241/26310872/abde1086-3f02-11e7-8797-c384e5afde63.png)
![solutionexplorer](https://cloud.githubusercontent.com/assets/7635241/26310871/abd13e56-3f02-11e7-8b60-91b8bee70243.png)

**Comment by eshupps** [comment]
Did you use the release version linked from the Release page, install from the Visual Studio gallery, or clone the repo and do a local build?

**Comment by bonm014** [comment]
Oh sorry ofcourse, I used the version from the "Visual Studio Extension Gallery"

**Comment by eshupps** [comment]
Fixed in #55b7d20.
