### ISSUE TITLE
Visual Studio Crash in cancel

### ISSUE THREAD

**Issue by bonm014** [SharePoint/sp-dev-fx-vs-extension#7]
#### Category
[ ] Question
[X] Bug
[ ] Enhancement

#### Expected or Desired Behavior
I would expect that when I click on cancel the wizard closes and no files are created

#### Observed Behavior
Visual studio crashes and the project folder is created, but no files

#### Steps to Reproduce
- Open visual studio 2015
- Create a SPF webpart within a new project.
- Click on cancel the wizard displays

**Comment by pschaeflein** [comment]
Technically, not a crash. Rather VS closes. But your point is understood.

**Comment by bonm014** [comment]
True! The same behavior with Visual Studio 2017

**Comment by eshupps** [comment]
Fixed in #55b7d20.
