### ISSUE TITLE
How to open existing project created using cmd and configure the F5 Action?

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-dev-fx-vs-extension#9]
#### Category
[ ] Question
[ ] Bug
[X ] Enhancement

#### Expected or Desired Behavior
f5 shall run the workbench on project created outside of Visual studio

#### Observed Behavior
The extension do not do the necessary operation for the F5 to run the workbench on SPFX project created from CMD, not from VS. Is there additional configuration to do ?

#### Steps to Reproduce
Create a SPFX project using CMD.exe
Open this folder with visual studio
Press F5

Thank you in advance for the great work

**Comment by eshupps** [comment]
The extension wasn't designed to be used with existing SPFx projects, only those created inside of the Visual Studio IDE. But we will look into it and see if that is possible. Thanks for the suggestion.
